echo off 
cls                                                                                                                                                          
echo                       .......                                
echo                     ...  . .....                             
echo                    ..... .    ....                           
echo                  .......... ..   ..                          
echo                 ......   .. .  . ...                         
echo                  ....     ..    ....                         
echo                 .....     ..  .   .... .........             
echo             ... .. .........  .    .. . . .   .....          
echo           ...   .     .. .. .      . . .        ...          
echo           ..       .      .    .   ..      .   .   .         
echo          ..  .......     . . .       .    ........ ..        
echo          .. ..    ....  .   ..   .    . ...      ....        
echo           ....      .                   ..        .....      
echo             .....   .  ......  .......  .         .. ..      
echo             .....   .. ..  ... .... ... .         .....      
echo              ...    . ...... .... .. ....                    
echo                     ..   . ......  .   ..                    
echo                      .   .   .. .   .  ..                    
echo                       .  .   ....    ...                     
echo                       ..   . ....    ..                      
echo                        ... ....... ...                       
echo                         .............                        
echo                            .........                         
echo                            ...........                       
echo                           ............                       
echo                           ....... ...                        
echo                           .  .......                         
echo                           .  ... ..                          
echo                           ........                          
echo                           .. . ..            						
echo			      W E L C O M E                                                                                                                                                                                                      
color 7                                                                                                   
                                                                                                    


python -m pip install -r requirements.txt
pause
